[package]
name = "mutsuki-cli-host"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow.workspace = true
clap.workspace = true
crossterm.workspace = true
ratatui.workspace = true
tokio.workspace = true
mutsuki-service-control.workspace = true
mutsuki-service-ipc.workspace = true

[lints]
workspace = true
