[package]
name = "mutsuki-std-service-host-integration"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mutsuki-plugin-image-render.workspace = true
mutsuki-plugin-io-browser-chromium.workspace = true
mutsuki-plugin-io-http-client.workspace = true
mutsuki-plugin-resource-memory.workspace = true
mutsuki-plugin-resource-sqlite.workspace = true
mutsuki-runtime-core.workspace = true
mutsuki-service-runtime.workspace = true
mutsuki-std-plugins.workspace = true
serde_json.workspace = true

[lints]
workspace = true
