import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile, readdir, stat } from "node:fs/promises";
import path from "node:path";
import * as esbuild from "esbuild";

export const SHARED_EXTERNALS = [
  "vue",
  "vue-router",
  "pinia",
  "@mutsuki/web-sdk",
  "@mutsuki/ui",
] as const;

export interface BuildOptions {
  entry: string;
  outDir: string,
  extensionId: string;
  version: string;
  capabilities?: string[];
  permissions?: string[];
  protocolVersion?: string;
  /** Development HMR is opt-in and never used by production WebHost. */
  hmr?: boolean;
}

export interface BuildResult {
  manifestPath: string;
  entryFile: string;
  assets: Array<{ path: string; content_hash: string; bytes: number }>;
}

function contentHash(bytes: Buffer): string {
  return `sha256:${createHash("sha256").update(bytes).digest("hex")}`;
}

async function walkFiles(root: string): Promise<string[]> {
  const out: string[] = [];
  async function walk(dir: string) {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(full);
      } else {
        out.push(full);
      }
    }
  }
  await walk(root);
  return out;
}

/**
 * Production build: Vue/TS/CSS precompiled to browser ESM.
 * WebHost runtime never invokes this tool.
 */
export async function buildExtension(options: BuildOptions): Promise<BuildResult> {
  if (options.hmr) {
    // HMR is a development aid only; production host must not depend on Vite/Node.
    console.info("[mutsuki-web-build] HMR mode requested for development tooling only");
  }

  await mkdir(options.outDir, { recursive: true });
  const outfile = path.join(options.outDir, "index.js");

  await esbuild.build({
    entryPoints: [options.entry],
    outfile,
    bundle: true,
    format: "esm",
    platform: "browser",
    target: ["es2022"],
    external: [...SHARED_EXTERNALS],
    // Vue SFC plugins can be added by callers; default path accepts pre-transformed TS/JS entry.
    logLevel: "silent",
  });

  const files = await walkFiles(options.outDir);
  const assets = [];
  for (const file of files) {
    if (path.basename(file) === "manifest.json") continue;
    const bytes = await readFile(file);
    assets.push({
      path: path.relative(options.outDir, file).replaceAll("\\", "/"),
      content_hash: contentHash(bytes),
      bytes: bytes.byteLength,
    });
  }

  const manifest = {
    manifest_version: 1,
    id: options.extensionId,
    version: options.version,
    entry: "index.js",
    capabilities: options.capabilities ?? [],
    permissions: options.permissions ?? [],
    assets,
    protocol_version: options.protocolVersion ?? "1.0.0",
  };
  const manifestPath = path.join(options.outDir, "manifest.json");
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

  // Fail if a shared runtime was accidentally bundled.
  const entrySource = await readFile(outfile, "utf8");
  for (const external of SHARED_EXTERNALS) {
    // Heuristic: bundled vue runtime markers should not appear.
    if (external === "vue" && entrySource.includes("Vue runtime DOM")) {
      throw new Error(`shared dependency '${external}' appears bundled`);
    }
  }

  return { manifestPath, entryFile: outfile, assets };
}

export async function checkExternals(outDir: string): Promise<string[]> {
  const files = await walkFiles(outDir);
  const warnings: string[] = [];
  for (const file of files) {
    if (!file.endsWith(".js")) continue;
    const source = await readFile(file, "utf8");
    const size = (await stat(file)).size;
    if (size > 512 * 1024) {
      warnings.push(`${file} exceeds 512KiB budget (${size} bytes)`);
    }
    if (source.includes("node:fs") || source.includes("from \"fs\"")) {
      warnings.push(`${file} references Node fs APIs`);
    }
  }
  return warnings;
}

/**
 * Development-only Vite config snippet. Production WebHost never loads Vite.
 * Callers may write this file and run `vite` during plugin authoring.
 */
export function createViteHmrConfig(options: {
  entry: string;
  root?: string;
}): string {
  const root = options.root ?? ".";
  return `import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// Generated by @mutsuki/web-build — development only.
export default defineConfig({
  root: ${JSON.stringify(root)},
  plugins: [vue()],
  build: {
    lib: {
      entry: ${JSON.stringify(options.entry)},
      formats: ['es'],
      fileName: () => 'index.js',
    },
    rollupOptions: {
      external: ${JSON.stringify([...SHARED_EXTERNALS])},
    },
  },
  server: {
    hmr: true,
  },
})
`;
}
