[package]
name = "mutsuki-plugin-image-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
html-escape.workspace = true
image.workspace = true
mutsuki-protocol-image.workspace = true
mutsuki-runtime-contracts.workspace = true
mutsuki-runtime-core.workspace = true
mutsuki-runtime-sdk.workspace = true
qrcode.workspace = true
serde.workspace = true
serde_json.workspace = true
takumi = { version = "2.5.7", features = ["from-html"] }

[dev-dependencies]
mutsuki-plugin-resource-memory = { path = "../mutsuki-plugin-resource-memory" }
tempfile.workspace = true

[lints]
workspace = true
