[package]
name = "mutsuki-std-plugins"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mutsuki-plugin-io-browser-chromium.workspace = true
mutsuki-plugin-io-http-client.workspace = true
mutsuki-plugin-image-render.workspace = true
mutsuki-plugin-resource-memory.workspace = true
mutsuki-plugin-resource-sqlite.workspace = true
mutsuki-runtime-contracts.workspace = true

[lints]
workspace = true
