[package]
name = "mutsuki-config-service"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Host-neutral transactional configuration service."

[dependencies]
mutsuki-config-derive = { workspace = true }
mutsuki-protocol-config = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
criterion = { version = "0.8.2", features = ["html_reports"] }
rmp-serde = { workspace = true }

[[bench]]
name = "config_perf"
harness = false
