[package]
name = "mutsuki-plugin-io-browser-chromium"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
headless_chrome.workspace = true
mutsuki-protocol-browser.workspace = true
mutsuki-runtime-contracts.workspace = true
mutsuki-runtime-core.workspace = true
mutsuki-runtime-sdk.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true

[lints]
workspace = true
