[package]
name = "mutsuki-service-abi-fixture"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mutsuki-runtime-contracts = { git = "https://github.com/sena-nana/MutsukiCore.git", rev = "b47bc9656c0990be3444af5975a203c7cb57825b" }
mutsuki-runtime-core = { git = "https://github.com/sena-nana/MutsukiCore.git", rev = "b47bc9656c0990be3444af5975a203c7cb57825b" }
mutsuki-runtime-sdk = { git = "https://github.com/sena-nana/MutsukiCore.git", rev = "b47bc9656c0990be3444af5975a203c7cb57825b" }
serde_json = "1.0"
