[package]
name = "mutsuki-plugin-bot-mihuashi"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
mutsuki-bot-link-parser.workspace = true
mutsuki-bot-protocol.workspace = true
mutsuki-protocol-browser.workspace = true
mutsuki-protocol-image.workspace = true
mutsuki-runtime-contracts.workspace = true
mutsuki-runtime-core.workspace = true
mutsuki-runtime-sdk.workspace = true
reqwest.workspace = true
scraper.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true

[dev-dependencies]
image.workspace = true
mutsuki-plugin-image-render-skia.workspace = true
mutsuki-plugin-io-browser-chromium = { path = "../../../std/plugins/mutsuki-plugin-io-browser-chromium" }
mutsuki-plugin-resource-memory = { path = "../../../std/plugins/mutsuki-plugin-resource-memory" }
mutsuki-service-config.workspace = true
mutsuki-service-control.workspace = true
mutsuki-service-runtime.workspace = true
tempfile.workspace = true
tokio.workspace = true

[lints]
workspace = true
