[package]
name = "mutsuki-link-tcp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Opt-in TCP transport for MutsukiLink"

[dependencies]
mutsuki-link-core.workspace = true
mutsuki-link-io.workspace = true
socket2.workspace = true
tokio.workspace = true

[dev-dependencies]
mutsuki-link-transport-testkit.workspace = true

[lints]
workspace = true
